-- OpenPlantDB — PostgreSQL table.
-- Load the full dataset with:  psql "$DSN" -f schema/plants.sql
-- (schema/plants.sql = this file + one UPSERT per plant, regenerated by build.py)
CREATE TABLE IF NOT EXISTS plants (
    slug                 TEXT PRIMARY KEY,
    common_name          TEXT NOT NULL,
    scientific_name      TEXT,
    category             TEXT,
    subcategory          TEXT,
    germ_days_min        INT,
    germ_days_max        INT,
    germ_soil_temp_f_min INT,
    germ_soil_temp_f_max INT,
    maturity_days_min    INT,
    maturity_days_max    INT,
    maturity_from        TEXT,
    sow_method           TEXT,
    season               TEXT,
    frost_tolerance      TEXT,
    plant_anchor         TEXT,
    plant_weeks_min      INT,
    plant_weeks_max      INT,
    plant_note           TEXT,
    usda_zone_min        INT,
    usda_zone_max        INT,
    spacing_in_min       REAL,
    spacing_in_max       REAL,
    height_in_min        REAL,
    height_in_max        REAL,
    spread_in_min        REAL,
    spread_in_max        REAL,
    sun                  TEXT,
    water                TEXT,
    directions           TEXT,
    sources              JSONB NOT NULL DEFAULT '[]',
    data                 JSONB NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_plants_category ON plants(category);
CREATE INDEX IF NOT EXISTS idx_plants_common   ON plants(lower(common_name));
